spring:
  datasource:
    username: postgres
    password: qwerty
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  config: logback-spring.xml
jwt:
  token:
    secret: soymun
    validate: 3600000
toFile:
  url: src/main/resources/files/